name: scanales_test1
favicon: null
layout_spectrum: 0.35114018409512937
typography_spectrum: 0.31674095266498625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.644621696555987
  lightness: 0.001960419351235032
  saturation: 0.8691906766034663
  rhythmicContrast: 0.6436510279309005
purpose: []
